### ISSUE TITLE
Remove the ability to set monthly price and price for RCI buildings

### ISSUE THREAD

**Issue by svetikas** [JustAnyones/Plugin-creator-website#15]
Although these attributes are supported, they are essentially ignored by the game so it makes sense to disallow usage of these attributes through PCA.

**Comment by ghost** [comment]
Rather than having their text fields disabled they should have not shown in the optional attributes dropdown

**Comment by 1Code-JS** [comment]
disab**l**ed*

**Comment by ghost** [comment]
![Screenshot_20241025-084514_TheoTown](https://github.com/user-attachments/assets/f4a26197-63a1-4578-b0b3-d4b5f6319d5c)
