### ISSUE TITLE
Figure out a better automatic ID generator

### ISSUE THREAD

**Issue by svetikas** [JustAnyones/Plugin-creator-website#5]
As it stands now, part of the ID can be considered random and not easily readable. A good choice would be to choose an ID that is readable and editable by the plugin creator.

**Comment by LobbyDivinus** [comment]
Ideally each author uses like a prefix e.g. $lobby_ that can be somewhat persistent by storing it in the browser. Assuming that different authors would use different prefixes this would reduce the need for strong random ids.

**Comment by svetikas** [comment]
So my current idea would be to have it something like

$authorName.pca.draftType.dateWithTime

This keeps it readable and ensures that it doesn't collide with plugins made a while ago by the same author.

**Comment by svetikas** [comment]
Actually, ditch the pca part. PCA plugins are identified by the meta tag.

**Comment by LobbyDivinus** [comment]
Looks nice
